#
# .dotter/skel/local_ubuntu.toml
# This file will be copyied by 00_prepare_linux.sh
#

includes = [".dotter/include/ubuntu.toml"]
packages = ["default", "bash", "vim", "tmux", "ruby", "direnv", "bin", "local_bin", "ssh"]

[files]
"home-dir/inputrc" = "~/.inputrc"

[variables]
git_username =
email =
podman_port = 5000
