#
# .dotter/skel/local_windows.toml
# This file will be copyied by prepare_windows.bat
#

includes = [".dotter/include/windows.toml"]
packages = ["default"]

[files]

[variables]
git_username =
email =
podman_port = 5000