---
- name: Check vars
  hosts: "localhost"
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - debug:
        msg: "DOT_DIR: {{ DOT_DIR }}"
    - debug:
        msg: "username<email>: {{dot_username}}<{{ dot_email }}>"

- name: dotiflesの最新化
  hosts: "!localhost"
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - git:
        repo: "https://github.com/tetsuyainfra/dotfiles.git"
        dest: ~/dotfiles
        update: yes

- name: 基本設定
  hosts: "localhost"
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - import_tasks: "tasks/basic_configs.yml"

- name: Role Setting
  hosts: "localhost"
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  roles:
    - "zzet.rbenv"
