---
- name: Check vars
  hosts: "localhost"
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - debug:
        msg: "DOT_DIR: {{ DOT_DIR }}"
    - debug:
        msg: "username<email>: {{dot_username}}<{{ dot_email }}>"

- name: dotiflesの最新化
  hosts: "!localhost"
  gather_facts: no
  vars_files:
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - git:
        repo: "https://github.com/tetsuyainfra/dotfiles.git"
        dest: ~/dotfiles
        update: yes

- name: 基本設定
  hosts: "localhost"
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - import_tasks: "tasks/basic_configs.yml"

- name: Setting with Role
  hosts: "localhost"
  vars:
    rbenv_users:
      # - tetsuyainfra # hardcodeなので・・・
      # with_itemsだとだめ
      # https://www.reddit.com/r/ansible/comments/eo6lwq/why_is_ansible_user_not_defined_when_accessed/
      # - "{{ ansible_user }}"
      - "{{ ansible_env['USER'] }}" # workaround
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  roles:
    # - role: "zzet.rbenv"
    - role: "markosamuli.pyenv"

# - name: DEBUG
#   hosts: "localhost"
#   vars_files:
#     - "{{ playbook_dir }}/vars/dotfiles.yml"
#     - "{{ playbook_dir }}/vars/dot_vars.yml"
#   tasks:
#     - name: "ansible_user is tetsuyainfra"
#       debug:
#         msg: "{{ ansible_user }}"
#     - name: "become:yes ansible_user is tetsuyainfra"
#       become: yes
#       debug:
#         msg: "{{ ansible_user }}"
#     - name: "ansible_user is tetsuyainfra"
#       debug:
#         msg: "{{ ansible_env['USER'] }}"
#     - name: "become:yes ansible_user is tetsuyainfra"
#       become: yes
#       debug:
#         msg: "{{ ansible_env['USER'] }}"