---
- name: Check vars
  hosts: "localhost"
  vars_files:
    - "{{ playbook_dir }}/vars/dotfiles.yml"
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - debug:
        msg: "DOT_DIR: {{ DOT_DIR }}"
    - debug:
        msg: "username<email>: {{dot_username}}<{{ dot_email }}>"

- name: dotiflesの最新化
  hosts: "!localhost"
  vars_files:
    - "{{ playbook_dir }}/vars/dot_vars.yml"
  tasks:
    - git:
        repo: "https://github.com/tetsuyainfra/dotfiles.git"
        dest: ~/dotfiles
        update: yes