[helpers]

[default]
depends = ["git"]

[default.files]

[default.variables]

#------------------------------------------------------------
# ~/.bin
#------------------------------------------------------------
[bin]
[bin.files]
# direcotryをsymbolic linkとして作成
bin = { target = "~/.bin", type = "symbolic" }

#------------------------------------------------------------
# Git
#------------------------------------------------------------
[git]
[git.files]
git = "~/.config/git"

#------------------------------------------------------------
# Bash
#------------------------------------------------------------
[bash]
[bash.files]
"bash/bash_aliases" = "~/.bash_aliases"
"bash/bash_profile" = "~/.bash_profile"
"bash/bash_completion.d" = { target = "~/.bash_completion.d",  type = "symbolic" }

#------------------------------------------------------------
# VIM
#------------------------------------------------------------
[vim]
[vim.files]
"vim" = { target = "~/.vim",  type = "symbolic" }

#------------------------------------------------------------
# tmux
#------------------------------------------------------------
[tmux]
[tmux.files]

#------------------------------------------------------------
# direnv
#------------------------------------------------------------
[direnv]
[direnv.files]
"direnv" = "~/.config/direnv"

#------------------------------------------------------------
# ruby
#------------------------------------------------------------
[ruby]
[ruby.files]
"ruby/gemrc" = "~/.gemrc"