[helpers]

[default]
depends = ["git"]

[default.files]

[default.variables]

#------------------------------------------------------------
# Git
#------------------------------------------------------------
[git]

[git.files]
git = "~/.config/git"

#------------------------------------------------------------
# Inputrc
#------------------------------------------------------------
[inputrc]
[inputrc.files]

#------------------------------------------------------------
# Windows
#------------------------------------------------------------
[bash]