# tetsuyainfra/dotfiles/zsh/zshrc

## zplug
export ZPLUG_HOME=$ZDOTDIR/zplug
source $ZPLUG_HOME/init.zsh

# To manage zplug itself
zplug 'zplug/zplug', hook-build:'zplug --self-manage'

# plugins
zplug mafredri/zsh-async, from:github
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

zplug "mollifier/anyframe"
zplug "mollifier/cd-gitroot"

# input emoji on cli Ctrl+s
# $ git commit -m 'This docume^s ...
# $ echo ":santa^s" | emojify
zplug "b4b4r07/emoji-cli"

# zplug "b4b4r07/enhancd", use:init.sh

zplug "zsh-users/zsh-history-substring-search"

zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "zsh-users/zsh-completions"

## Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
  printf "Install? [y/N]: "
  if read -q; then
    echo; zplug install
  fi
fi

zplug load

### zplugin
#source ~/.zsh/zplugin/bin/zplugin.zsh
#
## Two regular plugins loaded without tracking.
#zplugin light zsh-users/zsh-autosuggestions
#zplugin light zdharma/fast-syntax-highlighting
#
#zplugin load zdharma/history-search-multi-word
#
## pure is prompt theme
#zplugin ice pick"async.zsh" src"pure.zsh"
#zplugin light sindresorhus/pure
#
## select menu like peco
#zplugin ice from"gh-r" as"program"
#zplugin load junegunn/fzf-bin
#
#autoload -Uz _zplugin
#(( ${+_comps} )) && _comps[zplugin]=_zplugin